### ISSUE TITLE
Oak Flower Tub isn't a valid job site

### ISSUE THREAD

**Issue by drakray** [finallion/VillagersPlus#14] opened 2023-09-07 05:00 UTC
using:
Minecraft 1.20.1
NeoForge 47.1.76
VillagerPlus 3.0
BunchaOtherMods™

Other FlowerTub seem valid

**Comment by drakray** [comment] 2023-09-07 05:00
Villager seem to take a job from Oak, but stay Unemployed

**Comment by ImpulsiveLass** [comment] 2023-09-21 21:01
Can verify, only oak has the issue (you can tell they try based on the being hired particle but they remain unemployed) 
All other tubs work as intended

**Comment by finallion** [comment] 2023-12-31 15:22
Fixed in 3.1

**Closed as completed by finallion** 2023-12-31 15:22 UTC
Labels: bug
